### PR TITLE
Added SCSS Compatibility

### PR DESCRIPTION
**Pull request by tomvanenckevort**
In order to ease the use of Lightpick by frontend developers who use SCSS for generating their stylesheets, I've included a SCSS file for Lightpick.

### Why
Currently when you want to set custom colours or font settings for the Lightpick control, you would have to include a CSS override after the default Lightpick stylesheet has been included. For example:
```
<link rel="stylesheet" type="text/css" href="css/lightpick.css">
<style>
  .lightpick__day.is-today {
    color: #6BD16F;
  }
</style>
```
(most people would include this in their own stylesheet, but this is just a simplified example)

This means you're loading both the existing stylesheet and the overrides which adds some extra overhead.
By utilising SCSS and setting up some variables to control things like colours and font sizes, it becomes easier to set the correct defaults for your particular site without the overhead of overrides.

This provides an additional option to frontend developers who use SCSS and doesn't affect how Lightpick gets used by existing users, so it won't break anything there.

### How
I've includes a `lightpick.scss` file that uses the exact same stylesheets as the default `lightpick.css` and has variables added to set things like colours, font settings and calendar size.
To use it you would do the following:
```
/ * Set the variables for any settings you wish to override. 
    Anything not set will use the default variable value set in the lightpick.scss file */
$lightpick-today-color: #6BD16F;

/* import the SCSS file */
@import 'node_modules/lightpick/scss/lightpick';

/* your other styles ... */
```
(SCSS will then compile this to a CSS file)

### Test
You can either test this PR by including it in your SCSS workflow and check that the right styles get generated and included, or alternatively you can test it by pasting the contents of the `lightpick.scss` file into [SassMeister](https://www.sassmeister.com/) and check that the compiled output matches the default styles of `lightpick.css`.

### CODE REVIEW

**Comment by mehruncodes** [comment]
@wakirin We need this!

**Comment by Jaska** [comment]
+1 for this!

**Comment by sinankeskin** [comment]
Hey @tomvanenckevort 

On [SassMeister](https://www.sassmeister.com/) only libsass compile successfully.

Other compilers shows an error. I think this is a problem.
If you solve this I'll merge immediately.

Thanks for the PR.

**Comment by tomvanenckevort** [comment]
Hi @sinankeskin,

I've updated some of the variable definitions to make sure they work in the various compilers.

It is still showing an error in the Sass v3.3.14 compiler on Sassmeister, but I'm not sure if that is possibly due to a bug there (some other valid gists fail as well in that compiler version). 
That version is from 2016, so I don't think we need to support a Sass version that old.

**Comment by sinankeskin** [comment]
Thanks for the effort @tomvanenckevort

**Pull request merged**
