### PR TITLE
Added date selector accessibility

### PR DESCRIPTION
**Pull request by scssyworks**

### CODE REVIEW

**Comment by wakirin** [comment]
I don't see any problem with accessibility.
Can you explain please why we need use `button` instead of `div` ?

**Comment by scssyworks** [comment]
Hi wakirin
The scenario is when we are using embedded calendar view (where calendar input field is hidden), user should be able to navigate and select date via keyboard. Let me know if you have better suggestion to handle that. May be I am missing something.
Thanks
Sachin Singh

**Comment by scssyworks** [comment]
Hi @wakirin ,
I haven't heard from you in a while. Let me know if I need to update anything in the PR.
Thanks
Sachin Singh

**Comment by scssyworks** [comment]
Closing this PR

**Pull request closed without merging**
